#!/usr/bin/env python3

from flask import Flask, send_from_directory
import os
import sys

directory = ""

excluded_files = []

page_title = ""

if len(sys.argv) > 1 and sys.argv[1] != "":
    directory = sys.argv[1]
else:
    print("You must provide a directory that contains the files you want to serve.")
    exit(1)

if len(sys.argv) > 3 and sys.argv[2] == "--exclude":
    excluded_files = sys.argv[3].split(',') if len(sys.argv) > 3 else []
    if len(sys.argv) > 5 and sys.argv[4] == "--title":
        page_title = sys.argv[5]
    else:
        page_title = "Gabefgonc's Downloader"
elif len(sys.argv) > 2 and sys.argv[2] == "--title":
    page_title = sys.argv[3] if len(sys.argv) > 3 else "Gabefgonc's Downloader"
    if len(sys.argv) > 4 and sys.argv[4] == "--exclude":
        excluded_files = sys.argv[5]
    else:
        excluded_files = []



app = Flask(__name__)

@app.route('/')
def handle_request():
    html = "<body>"
    html += f"<h1 id='title'>{page_title}</h1>"
    file_list = os.listdir(directory)
    file_list.sort()
    for file in file_list:
        if file in excluded_files:
            continue
        html += f"<a class='file' href='/files/{file}'>Download: {file}</a> <br>"
    html += "</body>"
    html += '<head><style>.file { color: #415735; margin-top: 15px; text-decoration: none; margin-left: 30px; font-family: arial } #title { color: #32a852; text-align: center; font-family: arial }</style></head>'

    return html

@app.route('/files/<file>')
def handle_file(file):
    if file in excluded_files:
        return "File Not Found"
    if os.path.isdir(file):
        return "<h1>Can't Download a folder</h1>"

    return send_from_directory(directory, file)

if __name__ == '__main__':
   app.run()
